### ISSUE TITLE
Missing SSL Certificate on hackforhumanity.io

### ISSUE THREAD

**Issue by PatrickKan** [SCUACM/SCUACM.github.io#21]
Hey! I saw you guys are hosting a hackathon and were missing a SSL Cert on your website which I assume is [hackforhumanity.io](hackforhumanity.io)? 

I've had good experiences with Let's Encrypt or Cloudflare for setting that up, but it's definitely a web essential for any site with a lot of traffic! For more context, I'm one of the organizers of HackIllinois and checked out your hackathon too! :)

**Comment by rgajrawala** [comment]
Hi, thanks for reaching out. HTTPS is already supported - https://hackforhumanity.io/
